import { GitHubService, IncidentEvent, AgentResult } from "@devops-guardian/shared";

export class PRAgent {
  private github: GitHubService;

  constructor() {
    this.github = new GitHubService(""); // Initialize empty, must be set in execute
  }

  async execute(
    incident: IncidentEvent,
    patchData: any,
    rca: any,
    token: string,
  ): Promise<AgentResult> {
    console.log(`[PR Agent] Starting PR creation for ${incident.id}`);

    try {
      if (!token) {
        return { success: false, data: { error: "Missing GitHub Token for PR creation" } };
      }
      this.github = new GitHubService(token);

      const { owner, repo, fileUpdates } = patchData; // Expecting patchData to have this structure

      if (!owner || !repo || !fileUpdates) {
        return {
          success: false,
          data: { error: "Missing patch data (owner, repo, or updates)" },
        };
      }

      const branchName = `fix/incident-${incident.id.substring(0, 8)}-${Date.now()}`;

      // 1. Create Branch
      // Note: We need to know 'base' branch, assumed 'main' for now.
      await this.github.createBranch(owner, repo, "main", branchName);

      // 2. Commit Files
      for (const update of fileUpdates) {
        await this.github.commitFile(
          owner,
          repo,
          update.path,
          update.content,
          `fix: resolved incident ${incident.id}`,
          branchName,
        );
      }

      // 3. Create PR
      const rcaAnalysis = rca?.analysis || "No detailed analysis provided.";
      const patchSummary = patchData?.summary || "Applied automated patch.";

      const prBody = `
## 🛠️ Automated Fix for Incident #${incident.id.substring(0, 8)}

> **Status**: ✅ Verification Passed (E2B Sandbox)
> **Severity**: ${incident.severity}
> **Source**: ${incident.source}

### 📝 Summary
This PR resolves the critical incident **"${incident.title}"** detected in the ${incident.metadata?.errorSource || "production"} environment.

### 🔍 Root Cause Analysis
${rcaAnalysis}

### 🔧 Proposed Fix
${patchSummary}

#### Modified Files:
${fileUpdates.map((f: any) => `- \`${f.path}\``).join("\n")}

### 🧪 Verification
The fix has been verified in an isolated **E2B Sandbox** environment.
- [x] Build Successful
- [x] Unit Tests Passed
- [x] Integration Checks Passed

---
*Generated by [DevOps Guardian](https://github.com/ARYANjoshi09/DevOps-Guardian-)* 🦅
`;

      const pr = await this.github.createPullRequest(
        owner,
        repo,
        `fix: ${incident.title || "Automated Resolution"}`,
        prBody,
        branchName,
        "main",
      );

      console.log(`[PR Agent] PR Created: ${pr.url}`);
      return { success: true, data: { prUrl: pr.url } };
    } catch (error: any) {
      console.error("[PR Agent] Failed:", error);
      return { success: false, data: { error: error.message } };
    }
  }
}
